## Automate the creation of a new post using this script
## This generates a page.mdx file with the required defaults set and properlfy formatted
import time
import os

# Take the metadata from the user
title = input("Enter the title of the post: ")
description = input("Enter the description of the post: ")
tags = input("Enter the tags for the post: ")
date = input("Enter the date for the post(MM-DD-YYYY): ")
post_name = input("Enter the post name for the post(): ")
image = input("Enter the image path for the post: ")

current_year = time.strftime("%Y")
slug = current_year + "/" + post_name
folder_name = "./src/app/blog/posts/" + slug
file_name = folder_name + "/page.mdx"

# Create the folder
os.makedirs(folder_name)

# Create the file
with open(file_name, "w") as f:
    f.write("---")
    f.write("\n")
    f.write("title: " + title)
    f.write("\n")
    f.write("description: " + description)
    f.write("\n")
    f.write("tags: " + tags)
    f.write("\n")
    f.write("image: " + image)
    f.write("\n")
    f.write("slug: " + slug)
    f.write("\n")
    f.write("publishDate: " + date)
    f.write("\n")
    f.write("---")
    f.write("\n")
    f.write("\n")
    f.write("import MdxLayout from '@/components/mdx-layout'")
    f.write("\n")
    f.write("\n")
    f.write("export const metadata = {")
    f.write("\n")
    f.write("  title: '" + title + "',")
    f.write("\n")
    f.write("  description: '" + description + "',")
    f.write("\n")
    f.write("  tags: '" + tags + "',")
    f.write("\n")
    f.write("  year: '" + current_year + "',")
    f.write("\n")
    f.write("};")
    f.write("\n")
    f.write("\n")
    f.write("# " + title)
    f.write("\n")
    f.write("####")
    f.write("\n")
    f.write("## Description: " + description)
    f.write("\n")
    f.write("####")
    f.write("\n")
    f.write("### Tags: " + tags)
    f.write("\n")
    f.write("####")
    f.write("\n")
    f.write("####")
    f.write("\n")
    f.write("\n")
    f.write("!!!! WRITE YOUR CONTENT HERE !!!! ")
    f.write("\n")
    f.write("\n")
    f.write("export default function MDXPage({ children }) {")
    f.write("\n")
    f.write("   return <MdxLayout title='"+ post_name +"' year={metadata.year}> {children} </MdxLayout>")
    f.write("\n")
    f.write("}")
    f.write("\n")
