// This util is used to generate the table of contents for the markdown files

// Read the markdown file
import fs from 'fs'
import Link from 'next/link';

export default function genTOC(title:string,year:string) {
    const file = process.cwd() + '/src/app/blog/posts/'+year+'/'+title+'/'+'page.mdx';
    // Parse the file to get subheadings
    const fileContents = fs.readFileSync(file, 'utf8');
    // Get the subheadings
    let subheadings = fileContents.match(/(?<=^## ).+/gm);
    subheadings?.shift()

    // Create the list in which if we click a subheading, we are taken to that part of the page
    return (
        <>
        <ul className='space-y-10'>
            {subheadings?.map((subheading, index) => (
                <li key={index}>
                    {/* Replace spaces with hyphens */}
                    {/* We need to match the id's generated by rehype slug so that's why we replace spaces with hyphens and lowercase */}
                    <div className='flex flex-row space-x-3 text-xl'>
                        <span>--</span>
                        <Link className='text-lg transform transition hover:-translate-y-2
' href={`#${subheading.replace(/ /g, '-').toLowerCase()}`}>
                            {subheading}
                        </Link>
                    </div>
                </li>
            ))}
        </ul>
        </>
    )
}
